### PR TITLE
Add game mode show

### PR DESCRIPTION
**Pull request by oneheed**
Some people suggest that the order here is different from the game
So I changed a version to the same order as the game
Help me code review in trouble, thanks

### CODE REVIEW

**Comment by Eniwder** [comment]
looks good!
I think the algorithm is also proper.

**Comment by Eniwder** [comment]
After thinking a bit later, I found a way to not re-render when changing game-modes, so I changed the algorithm a bit. 
see also: https://github.com/Eniwder/artactree/commit/2797297c370c78647ccd3c5a3ef102899f29ef0c#diff-c2770e60ef78d13cad5b506461844da2d0087351bef71d104bff1586236be166

**Comment by oneheed** [comment]
I think we still have to re-render
game-modes expected effect
image

origin effect
image

**Comment by oneheed** [comment]
Can I ask you a question

```
<v-btn :value="herotyype">
  <v-img
    contain
    width="24px"
    max-height="32px"
    :src="`./assets/res/role_${herotyype}png`"
  ></v-img>
  {{ this.appLaunages.filterRole.attacker }}
</v-btn>
```
why img can not show?

please help me, thank

**Comment by Eniwder** [comment]
1. gamemode bug
I'm sorry, there was a bug when displaying horizontally.
However, It fixed by changing the rules of the css class.
please check.

2. problem of show img
It may solve using `require()`.
see also:https://stackoverflow.com/questions/55152795/vue-js-data-binding-not-working-for-img-src

**Comment by oneheed** [comment]
Need add watch

change horizon, sometime have question 

    'opts.horizon'() {
      this.adjustHeight();
    },

**Comment by Eniwder** [comment]
ok. thanks.
It fixed.
https://github.com/Eniwder/artactree/commit/ce964b0130a136b3b9d5c16f23dd5b69d8c2829e#diff-c2770e60ef78d13cad5b506461844da2d0087351bef71d104bff1586236be166

**Pull request merged**
